### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by dubiousdavid** [appuri/robust-websocket#2]
Latest on npm is `0.1.0`.

**Comment by nathanboktae** [comment]
Done, thanks for the reminder!

**Comment by dubiousdavid** [comment]
I'm still not seeing `0.2.0` on npm. Does it normally take longer than 30 minutes for it to propagate?

**Comment by dubiousdavid** [comment]
It's there now. Thanks!

**Comment by nathanboktae** [comment]
Yeah it was likely a couchdb replication lag.
